### ISSUE TITLE
The PDF's Page 61 has misplaced image at the bottom of the page

### ISSUE THREAD

**Issue by fnorf** [scipy-lectures/scipy-lecture-notes#239]
The PDF's Page 61 has a misplaced image at the bottom of the page, see 
![untitled](https://cloud.githubusercontent.com/assets/279583/17211408/a247c464-54c9-11e6-905c-5a12599489f0.png)

**Comment by pdebuyl** [comment]
Thank you for the report.

I cannot reproduce with the current head or with the version tagged 2015.2, can you or one of the maintainers reproduce this bug?

**Comment by gertingold** [comment]
I cannot reproduce it with the current head. The figure in question now appears on top of page 67. On the other hand, the output on page 56 is overlapping the footer (using Sphinx 1.5.3).

**Comment by pdebuyl** [comment]
sphinx-build 1.4.9, I have an overlap on the footer of page 54 :-/

It is the latex verbatim environment that does not place itself right here.

**Comment by gertingold** [comment]
I wonder whether it would be a good idea to have a requirements file in order to obtain consistent results. Part of the version information could be taken from `.travis.yml`, but the Sphinx version is not defined there.

**Comment by pdebuyl** [comment]
I believe that the end result may depend on also the latex installation (versions of latex packages, etc). so a more robust solution would be needed, such as making those verbatim into floats.

**Comment by GaelVaroquaux** [comment]
> I believe that the end result may depend on also the latex installation
> (versions of latex packages, etc). so a more robust solution would be needed,
> such as making those verbatim into floats.

It might be good to do this on our CI server, to ensure such a robust
solution and point to the resulting PDF.

**Comment by gertingold** [comment]
I do not think that floats would be the solution. If code snippets can float around, the connection to the discussion of the code is lost and one is constantly searching for code. Interestingly, I never did experience problems with code not breaking correctly in my lecture notes produced in Sphinx (see https://gertingold.github.io). May be we need to look more into the details of the LaTeX code and identify the source of the problem. In order to do so, a well-defined environment to produce the PDF as proposed by @GaelVaroquaux might indeed be very useful to ensure that we know what we are talking about.

**Comment by pdebuyl** [comment]
Hi all,

The situation is much better now. I suspect that it is only because of update of sphinx, however :-)

There are no more overflowing images and mostly "not too much" overwide items.

The cache of the website is not updated yet, so some patience is needed to see the current notes.
