### ISSUE TITLE
Update image for numpy fancy indexing

### ISSUE THREAD

**Issue by surfer190** [scipy-lectures/scipy-lecture-notes#349]
In the image http://www.scipy-lectures.org/_images/numpy_fancy_indexing.png

It reads:

`mask = array([1,0,1,0,0,1], dtype=bool)`

but it should be:

`mask = np.array([1,0,1,0,0,1], dtype=bool)`

**Comment by pdebuyl** [comment]
Hi @surfer190 thank you for the notice.

Unfortunately, the source of the image is not part of the repository and it would be some work to redo-it. As the code there is not copy-pastable, the damage is minor. I label as wontfix and close. I'll reopen if there are more notifications of this flaw being a distration to users of the the lectures.

**Comment by gertingold** [comment]
If there is interest, I could redo it in Python (using [PyX](http://pyx.sourceforge.net), see [source](https://github.com/gertingold/euroscipy-numpy-tutorial/blob/master/images/src/array3d.py) and [PDF](https://github.com/gertingold/euroscipy-numpy-tutorial/blob/master/images/array3d.pdf) for an example). Formally, this would add a dependency on PyX, but on the other hand, the image would be in the repo so that there is no need to reproduce it during the build. And having a source is better than having none. But I will go ahead only if I get some encouragement...

**Comment by pdebuyl** [comment]
I am not super enthusiast with the idea of adding any dependendy, altough if the images are committed to the repo statically (no need of PyX for other developers and/or users), it'd be nice to fix this sometimes :-) Let's wait for encouragement.

**Comment by gertingold** [comment]
I completely agree and that is why I did not go ahead with recreating some of the figures, even though in my own work I like to have sources for the figures, making it easier to modify them in case of need.
