### ISSUE TITLE
Incorrect code alignment at p55, 3.1.5. 3.1.5 Indexing and slicing for Exercise: Array creation

### ISSUE THREAD

**Issue by yasokada** [scipy-lectures/scipy-lecture-notes#370]
In https://www.scipy-lectures.org/_downloads/ScipyLectures-simple.pdf
p55
Exercise: Array creation

The code is misaligned overlapping to the bottom of the page.

**Comment by pdebuyl** [comment]
Dear @yasokada 

Thank you for the report, it is very useful for us to receive feedback!

We are aware of the problem, which shares its origin with #239 so I close this issue. Your issue will be listed in the conversation of #239 so that it will not go unseen but the discussion remains in a single issue for us. In short, some LaTeX environments have trouble in keeping "in place" and we have no good solution yet.

Best regards,

Pierre

**Comment by yasokada** [comment]
Dear Pierre

I see.

For the related issues, I will follow #239.

Best regards

Yasuhiko OKADA
