### ISSUE TITLE
curve fitting of temperature data not so good

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#436]
In the "Curve fitting of temperature data" exercise in section "1.5.5.1. Curve fitting", the yearly_temps function is a much better fit if times.max() is replaced by 11. Note that I cannot explain why since times.max() == 11!

**Comment by gertingold** [comment]
The fits are precisely the same in the two cases as you can see by printing ``res_min`` and ``res_max``. However, the plot of the fitting curves differs because the argument ``times`` during fitting is given by ``months`` while during plotting it is given by ``days``. Note that ``months.max()`` and ``days.max()`` differ.

I am not sure whether point 4 of the exercise refers to this issue and I do not want to spoil it by explaining all details of what is going on here. However, I wonder whether it makes sense to have a fitting example which clearly uses an inappropriate fitting function. It will probably confuse many readers. After all, we are still in the introductory part of the lecture notes. If I get some encouragement, I could prepare a PR where this tricky point is removed.

@mcorne: Checking out what happens if ``times.max()`` is replaced by ``11`` was a great idea.

**Comment by mcorne** [comment]
Thanks for the explanation. Frankly I should have figured it out myself even if the plots misled me.
The exercise as it is looks good to me, feel free to close the issue.
