### ISSUE TITLE
unexpected gaussian filter sigma value

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#441]
In section "1.5.10.2. Image filtering", given that the purpose of the exercise is to filter the noise, it would make more sense to pass sigma=1 instead of 3 to the gaussian filter since the added noise is based on a standard normal distribution (sigma=1). We can then verify that the gaussian filter works as expected.

Same issue in section "1.5.12.16. Plot filtering on images".

As a side note, the median filter works better with a size=3.
Same for the wiener filter.
Again, assuming the idea is to remove the noise as well as possible.

**Comment by mcorne** [comment]
As a side note, the median filter works better with a size=3.
Same for the wiener filter.
Again, assuming the idea is to remove the noise as well as possible.

**Comment by pdebuyl** [comment]
Hi @mcorne thank you for the issue.

The sigma for the noise is the intensity of the noise while for the filter it represents the spatial extension of the filter, so that the two are not related by their sigma value. I don't think that specific values are necessary anyway as the point is to illustrate the filters.

Does that address the issue?

**Comment by pdebuyl** [comment]
Unless further questions arise, I consider the issue resolved.
