### ISSUE TITLE
Use sphinx-gallery's binder integration

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#458]
Sphinx-gallery now haw a binder integration, used eg in scikit-learn or mne-python.

We should set it up in sphinx-gallery. Ping @betatim @choldgraf @larsoner for help there

**Comment by betatim** [comment]
Because there is a `requirements.txt`/`environment.yml` in the repo already I tried to build it on mybinder.org to see what happens. Unfortunately conda thinks that there is a conflict between all the packages/versions asked for so it can't solve the environment. 

I've not tried setting up the environment locally to see if the conflict arises from a package repo2docker adds or if it is because we use Python 3.7 by default in repo2docker. Does someone know which version of Python was last used successfully for setting things up?

**Comment by betatim** [comment]
Found the answer to "which Python version" in the Travis config. For repo2docker the way to select a Python version if you use a `environment.yml` is to add `python=3.5` to it. Not sure how you want to handle that as the file is generated from the `requirements.txt`.

To test drive it with a manually fixed `environment.yml`: https://mybinder.org/v2/gh/betatim/scipy-lecture-notes/betatim-patch-1
