### ISSUE TITLE
circleci question

### ISSUE THREAD

**Issue by vahtras** [scipy-lectures/scipy-lecture-notes#459]
Hi you all. I spent a little time comparing details of travis and circleci, and if I am not mistaken circleci does not run the test suite at all, only a "make html" (in build_tools/circle_ci_test_doc.sh). Please correct me if I am wrong. Otherwise, unless it is a mistake, I am curious about the reason for this

Olav.

**Comment by pdebuyl** [comment]
@GaelVaroquaux can you confirm?

Ideally, we should use continuous integration to build a "devel" version of the website, as a complement to the released version (which has benefits as well).

**Comment by jarrodmillman** [comment]
We are using GH actions to run the tests now and circleci to build the docs. We are using circleci to build the docs since it allows you to view artifacts, which we do for devel version of the website using a GH action from @larsoner. It is a common pattern shared by many of the Scientiic Python core projects.
