### ISSUE TITLE
Recommend solve_ivp instead of odeint in section 6.7.2

### ISSUE THREAD

**Issue by guillermogf** [scipy-lectures/scipy-lecture-notes#483]
Hello!

I was reading the section 6.7.2 on numerical integration of differential equations and I feel like it might need some updating. The recommended way of doing it is to use [scipy.integrate.odeint](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html#scipy.integrate.odeint), but checking its documentation it recommends using [scipy.integrate.solve_ivp](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html#scipy.integrate.solve_ivp) instead.

I just came across this lecture notes yesterday, so I wouldn't know what kind of fix would be best. Whether it's rewriting the section with the new function, keeping both options or just referencing solve_ivp as one of those "Tips", I know not.

**Comment by pdebuyl** [comment]
Hello, thank you for the feedback. Indeed, now that SciPy has included solve_ivp since some time we can move to it as the default integrator example.

If you feel comfortable with the restructuredtext format, you can propose an edit of the file intro/scipy.rst

Make sure to read our contribution guidelines https://scipy-lectures.org/preface.html#contributing
